In [3]:
import pandas as ps

In [4]:
activity = ps.read_csv("./../activity_readings.csv")
stations = ps.read_csv("./../stations.csv")

In [5]:
activity.head()

  event_id         source_id             timestamp value
0   e00001   station-east-01  2026-09-09T08:00:00Z  26.6
1   e00002   station-east-02  2026-09-09T08:00:00Z  42.1
2   e00003  station-north-01  2026-09-09T08:00:00Z  44.5
3   e00004  station-north-02  2026-09-09T08:00:00Z  62.5
4   e00005  station-south-01  2026-09-09T08:00:00Z  93.4

In [6]:
stations.head()

         station_id           name sector       status
0  station-north-01    North Ridge  North       Active
1  station-north-02     North Gate  North       Active
2   station-west-01  West Junction   West       Active
3   station-west-02   West Outpost   West       Active
4   station-east-01    East Quarry   East  Maintenance

In [7]:
stations.drop_duplicates()

         station_id           name sector       status
0  station-north-01    North Ridge  North       Active
1  station-north-02     North Gate  North       Active
2   station-west-01  West Junction   West       Active
3   station-west-02   West Outpost   West       Active
4   station-east-01    East Quarry   East  Maintenance
5   station-east-02  East Crossing   East       Active
6  station-south-01   South Bridge  South       Active
7  station-south-02    South Field  South      Offline

In [8]:
activity.sum()

event_id     e00001e00002e00003e00004e00005e00006e00007e000...
source_id    station-east-01station-east-02station-north-01...
timestamp    2026-09-09T08:00:00Z2026-09-09T08:00:00Z2026-0...
value        26.642.144.562.593.466.0116.788.520.576.641.15...
dtype: str

In [9]:
activity[activity.duplicated(keep=False)]

Empty DataFrame
Columns: [event_id, source_id, timestamp, value]
Index: []

In [10]:
activity.info()

<class 'pandas.DataFrame'>
RangeIndex: 2092 entries, 0 to 2091
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   event_id   2090 non-null   str
 1   source_id  2090 non-null   str
 2   timestamp  2091 non-null   str
 3   value      2090 non-null   str
dtypes: str(4)
memory usage: 65.5 KB

In [11]:
stations.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   station_id  8 non-null      str
 1   name        8 non-null      str
 2   sector      8 non-null      str
 3   status      8 non-null      str
dtypes: str(4)
memory usage: 388.0 bytes